### ISSUE TITLE
在XML布局中增加控件并设置setLaserFrameTopMargin之后扫描的区域不准确

### ISSUE THREAD

**Issue by opencheer** [mylhyl/Android-Zxing#13]
是这样的，我在fragment中增加一个ToolBar和TabBar，然后设置setLaserFrameTopMargin使扫描框进行居中，发现在二维码离得特别近的时候扫描的识别率变低，经过反复试验应该是页面上的扫描区域与实际识别的区域出现偏差，另外如果扫描成功不跳转出现残影也是一个问题

**Comment by mylhyl** [comment]
感谢反馈，下班之后优化

**Comment by mylhyl** [comment]
扫描成功的残影：https://github.com/mylhyl/Android-Zxing/issues/9

**Comment by mylhyl** [comment]
请使用RelativeLayout布局，laserFrameTopMargin只计算了状态栏与标题栏的高度

**Comment by Swordce** [comment]
我设置只能靠上或者靠下，如何居中呢？

**Comment by mylhyl** [comment]
@Swordce 没有提供居中api，大部分扫描区域上下都是5:8比例，视觉效果比较适中，你可以先用setLaserFrameTopMargin调至居中，看看效果视觉如何，有必要的话再issues

**Comment by ACMNexus** [comment]
确实是的，我今天也在设置扫描框的位置之后，扫描的识别率就非常的低了，基本上就非常的难的扫描了。我那个时候以为是改变了文字的位置，后来发现我还修改了扫描框topMargin。请问一下如果我想在扫描框的下面加入一些控件要如何做呢？我还没有想到这个。

**Comment by mylhyl** [comment]
@ACMNexus 最外层用RelativeLayout

**Comment by chardlau** [comment]
@opencheer 
关于"发现在二维码离得特别近的时候扫描的识别率变低"的这个问题你有解决吗？
我在测试的时候，使二维码尽量与LaserFrame四边对齐的时候，发现基本无法扫描出来，反而把摄像头拿远一点就能成功。
