### ISSUE TITLE
识别速度有时候很慢，十几秒才识别出来，

### ISSUE THREAD

**Issue by herohd** [mylhyl/Android-Zxing#15]
希望能改善下识别速度上面有时候很慢，基本都要7,8秒以上。

**Comment by mylhyl** [comment]
debug模式下扫描、扫描电脑屏幕都将影响效率，你是什么场景下扫描的？

**Comment by herohd** [comment]
debug模式是指调试模式吗，还是说要设定什么模式的，扫的是手机上面的图片，会识别比较慢，

**Comment by hfbi360** [comment]
为什么debug模式下会影响效率？
