### ISSUE TITLE
在布局不是全屏情况下扫描框和解码的提取的图片不对应

### ISSUE THREAD

**Issue by yysnow** [mylhyl/Android-Zxing#22]
CameraManager中getFramingRectInPreview方法提取previewframe中扫描范围时，使用的计算方法是否不太准确，转换使用的是screenResolution是屏幕的大小，但实际上给用户看到的渲染范围有可能不是全屏的，因此转换是不是有误差，建议改为使用sufaceview的范围来计算：
Point screenResolution;
            if(sufaceRect != null){
                screenResolution = new Point(sufaceRect.right-sufaceRect.left,sufaceRect.bottom-sufaceRect.top);
            } else {
                screenResolution = configManager.getScreenResolution();//屏幕范围来近似摄像头渲染的范围
            }

sufaceRect在给摄像头设置holder时记录：
cameraObject.setPreviewDisplay(holder);
sufaceRect = holder.getSurfaceFrame()

**Comment by mylhyl** [comment]
欢迎提交pull request

**Comment by mylhyl** [comment]
这提交的啥啊~~~~

**Comment by yysnow** [comment]
现在在将摄像头里扫描范围取出来的时候是针对全屏按比例计算的，而不是按照sufaceview的大小来计算的，那么就存在看到二维码在扫描框实际一直扫描不出结果的情况
