### ISSUE TITLE
打开问题

### ISSUE THREAD

**Issue by familyCxp** [mylhyl/Android-Zxing#29]
在我自己的android项目中引用了zxingscanner，但是打开扫描二维码的页面总是打开已安装你这个demo的扫描二维码页面
<activity
            android:name=".ui.activity.ScannerActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:label="扫一扫">
        </activity>

**Comment by mylhyl** [comment]
在自己的项目`AndroidManifest.xml`文件中，找到扫描界面的act，重新配置`intent-filter -> action `，不要与demo中的相同
```xml
<activity
    android:name=".ScannerActivity"
    android:label="扫一扫">
    <intent-filter>
	<action android:name="com.mylhyl.zxing.scanner.client.android.SCAN" />
	<category android:name="android.intent.category.DEFAULT" />
    </intent-filter>
</activity>
```
