### ISSUE TITLE
是否条形码的返回结果没有进行解码处理？

### ISSUE THREAD

**Issue by namelin2** [mylhyl/Android-Zxing#3]
this method should be public ,not private
  private void onPause() { 
        if(this.mScannerViewHandler != null) {
            this.mScannerViewHandler.quitSynchronously();
            this.mScannerViewHandler = null;
        }

```
    this.mBeepManager.close();
    this.mCameraManager.closeDriver();
    if(!this.hasSurface) {
        SurfaceHolder surfaceHolder = this.mSurfaceView.getHolder();
        surfaceHolder.removeCallback(this);
    }

    this.mViewfinderView.laserLineBitmapRecycle();
}
```

**Comment by mylhyl** [comment]
Please update, the method already public

**Comment by namelin2** [comment]
Thanks.
能添加一下扫描条形码的功能吗，单单一个二维码的功能是否适用性不高？

**Comment by mylhyl** [comment]
本来是支持条形码扫描的，你有测试过？

**Comment by namelin2** [comment]
条形码扫了没反应了，我用书本的条形码扫了，没有反应，但是UC的二维码扫描可以扫除条形码的书本信息

**Comment by namelin2** [comment]
我用的是你的demo测试的

**Comment by namelin2** [comment]
现在测试了，可以扫了，但是没有返回结果

**Comment by namelin2** [comment]
![image](https://cloud.githubusercontent.com/assets/17449099/17549609/9cce96de-5f23-11e6-82d4-c50d7a0b8280.png)
扫描条形码后返回时空的，用log捕捉信息会报空指针错误

**Comment by namelin2** [comment]
这是一个蠢问题，尴尬

**Comment by mylhyl** [comment]
sample已经更新
