### ISSUE TITLE
颜色设置问题

### ISSUE THREAD

**Issue by AtlantaCaesar** [mylhyl/Android-Zxing#31]
使用setLaserFrameBoundColor()和setLaserColor() 方法无法正常为扫描四角与扫描线设置颜色。设置之后显示黑色。
`mScannerView.setLaserFrameBoundColor(R.color.colorPrimary);
        mScannerView.setLaserColor(R.color.colorPrimary);`

**Comment by mylhyl** [comment]
mScannerView.setLaserFrameBoundColor(getResources().getColor(R.color.colorPrimary));
mScannerView.setLaserColor(getResources().getColor(R.color.colorPrimary));
