### ISSUE TITLE
setLaserFrameTopMargin后nexus 5x下扫描框和扫描区域不一致

### ISSUE THREAD

**Issue by snailycy** [mylhyl/Android-Zxing#32]
![screenshot_20171115-144826](https://user-images.githubusercontent.com/9589433/32830537-1ee8c68c-c9bb-11e7-9932-738b4fab766d.jpg)

如图，在二维码区域时，才能识别出结果，在扫描框中识别不出，貌似是轴对称关系。
如果不设置LaserFrameTopMargin，扫描框在屏幕正中间时是没问题的。
ps：nexus 5x摄像头的旋转角度是270度

代码如下：

`mScanView = findViewById(R.id.scan_view);`
` mScanView.setLaserFrameTopMargin(50)
                .setLaserFrameSize(240, 240)
                .setOnScannerCompletionListener(this);`

**Comment by mylhyl** [comment]
mScanView.isScanFullScreen(false)是不是开启了全屏扫描？

**Comment by snailycy** [comment]
@mylhyl 
没有开启
在扫描框内识别不出，在扫描框下方可以识别出。如果扫描框设置成竖直居中就没问题了

**Comment by mylhyl** [comment]
[stackoverflow 解决 Nexus 5X](https://stackoverflow.com/questions/35448222/camera-view-is-upside-down-in-my-android-application-for-nexus-5x)
参考代码，可以尝试调转摄像头角度，我没有真机测试，欢迎pull requests！

**Comment by mylhyl** [comment]
[Nexus 5x reverse landscape sensor fix in a android camera preview app
](https://stackoverflow.com/questions/35414141/nexus-5x-reverse-landscape-sensor-fix-in-a-android-camera-preview-app)
```java
if (Build.MODEL.equals("Nexus 5x")){
     // rotate camera 180°
     mCamera.setDisplayOrientation(180);
}
```

**Comment by mylhyl** [comment]
[Nexus 5X records video rotated upside down using MediaRecorder and camera2
](https://stackoverflow.com/questions/34832098/nexus-5x-records-video-rotated-upside-down-using-mediarecorder-and-camera2)
```java
CameraManager manager = (CameraManager) activity.getSystemService(Context.CAMERA_SERVICE);
String cameraId = manager.getCameraIdList()[0];
CameraCharacteristics characteristics = manager.getCameraCharacteristics(cameraId);
int sensorOrientation = characteristics.get(CameraCharacteristics.SENSOR_ORIENTATION);

sensorOrientation value: Default camera orientation used to be 90 degrees. For Nexus 5X it is 270 degrees.
```

**Comment by snailycy** [comment]
谢谢作者耐心解答，但是mCamera.setDisplayOrientation 这个显示图像倒置问题是解决了的。如果有这个问题，上面那张图中的图像会是倒的

**Comment by snailycy** [comment]
![jietu20171215-142747](https://user-images.githubusercontent.com/9589433/34029569-36f6c5e8-e1a4-11e7-9f43-4a62ab707b99.jpg)

**Comment by mylhyl** [comment]
nexus 5x硬件问题导致，网上有说明是排线接反了，也有说法android 6.0系统已经解决，但还是希望你能测试一下找到原因所在。
照你所讲的描述，虽然预览角度是正常显示，有可能真是硬件问题导致camera转了180°，所以你可以尝试把camera再转180°，扫描识别区域是否正常。
顺便帮我测试一下，把扫描框设置到底部边缘后，扫描识别区域在哪？谢谢！

**Comment by snailycy** [comment]
试了下旋转180°，效果是预览会变成横屏的。
如果扫描框设置到底部后，真实识别区域在顶部，如图：

![jietu20171215-200238](https://user-images.githubusercontent.com/9589433/34041621-d293299a-e1d3-11e7-99c3-5ec32195c595.jpg)

**Comment by mylhyl** [comment]
@snailycy 收到，谢谢！
