### ISSUE TITLE
连续扫描，界面闪烁

### ISSUE THREAD

**Issue by jeesezh** [mylhyl/Android-Zxing#37]
当设置成连续扫描，调用restartPreviewAfterDelay方法清除残像，但是当时间设置未0的时候，界面就会闪烁
![image](https://user-images.githubusercontent.com/19542480/34337033-1ef0a626-e997-11e7-9ea0-6340c6261473.png)

**Comment by mylhyl** [comment]
扫描成功后的缩略图显示在界面上，默认是关闭的。把你的参数配置发一下

**Comment by mylhyl** [comment]
```javascript
compile 'com.mylhyl:zxingscanner:2.1.0'
```
此版本增加了你所说的残像控制方法，默认不显示残像，如需开启调用以下方法
```java
new ScannerOptions.Builder().setShowQrThumbnail(boolean)
```
