### ISSUE TITLE
扫描完跳转再返回扫描条框不见了

### ISSUE THREAD

**Issue by SmallYQ** [mylhyl/Android-Zxing#39]
扫描完做了跳转再返回扫描界面的时候，扫描的条框不见了，出现的是上一个界面的背景了。。。望赐教

**Comment by SmallYQ** [comment]
对了，它是偶尔会出现的，我在扫描界面处也调用了onresume的方法如下：
@Override
    protected void onResume() {
        super.onResume();
        scanner_view.onResume();
    }

**Comment by soaic** [comment]
我这边是在权限被拒绝后，弹出提示对话框，然后跳转到系统设置，再返回就出现扫描框不见
然后我这边改成了在onStart()中执行scanner_view.onResume(); onStop()中执行scanner_view.onPause();
好像就没问题了，你可以试试
