### ISSUE TITLE
获取闪光灯是否在开启的方法

### ISSUE THREAD

**Issue by GirlFriendNotFind** [mylhyl/Android-Zxing#40]
感谢开源，请问有没有获取闪光灯是否在开启的方法，不然感觉不好控制闪光灯，用自己的方法判断会有问题~

**Comment by mylhyl** [comment]
暂时没有，不过你可以把调用toggleLight(boolean light)方法参数作用域弄成成员变量。

**Comment by GirlFriendNotFind** [comment]
嗯~感谢建议
