### ISSUE TITLE
把扫描框设置在顶部的问题

### ISSUE THREAD

**Issue by shouzhong** [mylhyl/Android-Zxing#46]
我这边有个需求需要把扫描框设置在布局顶部，但是实际效果是顶部空出状态栏的高度，有没有办法把状态栏的那部分高度去掉吗？

**Comment by shouzhong** [comment]
我把frameTopMargin设置为负的状态栏高度解决了这个问题，还有作者能不能提供一个以px为单位的设置属性的方法，毕竟从配置文件中获取的尺寸都是px值，然后还要进行单位转换

**Comment by mylhyl** [comment]
感谢建议
