### ISSUE TITLE
Android5.1创建二维码报UnsupportedEncodingException: java.nio.charset.CharsetICU[UTF-8]

### ISSUE THREAD

**Issue by buyaomiege** [mylhyl/Android-Zxing#63]
解决方法
![Z %CUE6MD1N LOC~{GI9Q4H](https://user-images.githubusercontent.com/28820373/58304154-bb227c80-7e25-11e9-84e1-f02855d817e3.png)

**Comment by mylhyl** [comment]
收到，谢谢反馈！
